[package]
name = "portable-pty"
version = "0.2.0"
authors = ["Wez Furlong"]
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "Cross platform pty interface"
license = "MIT"
documentation = "https://docs.rs/portable-pty"

[dependencies]
async-trait = "0.1"
anyhow = "1.0"
filedescriptor = "0.7"
log = "0.4"
libc = "0.2"
shell-words = "0.1"
serde_derive = {version="1.0", optional=true}
serde = {version="1.0", optional=true}
serial = "0.4"
ssh2 = {optional=true, version="0.6"}

[features]
default = []
serde_support = ["serde", "serde_derive"]
ssh = ["ssh2"]

[target."cfg(unix)".dependencies]
mio = { version = "0.6" }
tokio = { version = "0.2", features = ["io-driver", "io-util"] }

[target."cfg(windows)".dependencies]
bitflags = "1.0"
lazy_static = "1.3"
shared_library = "0.1"
uds_windows = "0.1"
winapi = { version = "0.3", features = [
    "winuser",
    "consoleapi",
    "handleapi",
    "fileapi",
    "namedpipeapi",
    "synchapi",
]}

[dev-dependencies]
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
